delay support
gkaemmer/react-fade-in pull request #2
Opened 2017-06-08 07:25 UTC by adammoisa

2017-06-14 18:13 UTC, gkaemmer requested changes
Thanks for this! Just recommended a couple changes.

2017-06-14 18:13 UTC, gkaemmer commented on src/FadeIn.js
> +    var customLag = parseInt(this.props.lag) ? parseInt(this.props.lag) : 50;
Any reason to `parseInt` here? Might make the API simpler to just accept a number of milliseconds.

2017-06-14 18:13 UTC, gkaemmer commented on src/FadeIn.js
> +    }, customLag);
Just pass the prop directly here: `this.props.lag`.

2017-06-14 18:13 UTC, gkaemmer commented on src/FadeIn.js
> +    }, customLag);
Or maybe call the prop `delayStart`, so you have `delay` and `delayStart`. My guess is that `delay` is the more useful prop, but I'm not sure.

2017-06-14 18:13 UTC, gkaemmer commented on src/FadeIn.js
> +    const delay = this.props.delay;
`const delay = this.props.delay || 0;`

2017-06-14 18:13 UTC, gkaemmer commented on src/FadeIn.js
> +                'transition-delay': delay,
I'd CSS-ify the value for the user here:
```
transitionDelay: `${delay}ms`
```

2018-05-16 20:01 UTC, bcanseco commented
Just came across this PR - it'd be super cool to have this functionality in a new version of react-fade-in. @adammoisa any chance you're still looking to get this merged?

2018-05-16 20:31 UTC, gkaemmer commented
@bcanseco I went ahead and added `delay` and `transitionDuration` props: https://github.com/gkaemmer/react-fade-in/releases/tag/v0.1.6

2018-05-16 20:31 UTC, closed without merging