className prop for each fading element
gkaemmer/react-fade-in pull request #6
Opened 2020-01-15 16:34 UTC by Deveosys

Hey, it's me again ! 

I propose to pass a className prop applied for each fading element.
Feel free to find a better name if you deem it necessary.

2020-01-15 22:46 UTC, gkaemmer requested changes

2020-01-15 22:46 UTC, gkaemmer commented on src/FadeIn.js
> +              className={this.props.itemClassName}
Maybe call it `childClassName`?

2020-01-17 17:55 UTC, Henriii commented
Just commenting to let you know I'd also request this feature, or any other way to manipulate the style of the animated/fading divs.

2020-01-17 21:09 UTC, gkaemmer commented
Closing in favor of #7 -- thanks for a good idea! I'll give you credit for this change in the changelog.

2020-01-17 21:23 UTC, gkaemmer commented
This has been released in `0.1.8` as `childClassName`

2020-01-17 21:23 UTC, closed without merging